// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import static frc.robot.Subsystems.Elevator.ElevatorConstants.L2_POS;
import static frc.robot.Subsystems.Elevator.ElevatorConstants.L3_POS;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Commands.DriveCommands;
import frc.robot.Commands.ElevatorCommnads;
import frc.robot.POM_lib.Joysticks.PomXboxController;
import frc.robot.Subsystems.Drive.Drive;
import frc.robot.Subsystems.Elevator.Elevator;
//import frc.robot.Subsystems.Elevator.ElevatorIOSim;
import frc.robot.Subsystems.Elevator.ElevatorSparkMax;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in
 * the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of
 * the robot
 * (including subsystems, commands, and button mappings) should be declared
 * here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();
  private final PomXboxController operatorController = new PomXboxController(1);
  private final PomXboxController driverController = new PomXboxController(1);
  Elevator elevator;
  ElevatorCommnads elevatorCommnads;
  Drive drive;
  DriveCommands driveCommands;

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
   * The container for the robot. Contains subsystems, OI devices, and commands.
   */
  private RobotContainer() {
    switch (Constants.currentMode) {
      case REAL:
        elevator = new Elevator(new ElevatorSparkMax());

        break;

      case SIM:
        // elevator = new Elevator(new ElevatorIOSim());
        break;
    }

    elevatorCommnads = new ElevatorCommnads(elevator);
    configureButtonBindings();

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be
   * created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing
   * it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
    operatorController.y().onTrue(elevatorCommnads.runElevatorPIDFF(L3_POS));
    operatorController.x().onTrue(elevatorCommnads.runElevatorPIDFF(L2_POS));
    operatorController.b().onTrue(elevatorCommnads.elevatorDown());
    operatorController.a().onTrue(elevatorCommnads.runFF(10, 0));
    // operatorController.a().whileFalse(elevatorCommnads.runFF(0));
    operatorController.PovUp().whileTrue(elevatorCommnads.runElevator());
    operatorController.PovDown().whileTrue(elevatorCommnads.reverseElevator());
    operatorController.PovRight().onTrue(elevatorCommnads.runElevatorPIDFF(15));

    drive.setDefaultCommand(driveCommands.joystickDrive(drive, () -> driverController.getLeftY(),
        () -> driverController.getLeftX(), () -> driverController.getRightX()));
  }

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }

}